// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_N4KoulVAihi6yLHhMRR719cHtoxxEg',
    appId: '1:491750508291:web:2a7af6b75490b70720cb36',
    messagingSenderId: '491750508291',
    projectId: 'chatfirebase-c252a',
    authDomain: 'chatfirebase-c252a.firebaseapp.com',
    storageBucket: 'chatfirebase-c252a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99GVhyPVcPNfF4Nm14xGFOM5PpThJUXk',
    appId: '1:491750508291:android:db19e8e217b7623d20cb36',
    messagingSenderId: '491750508291',
    projectId: 'chatfirebase-c252a',
    storageBucket: 'chatfirebase-c252a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5q9i-uYp-ukrsgGN8gCk7o7AQTElLoJs',
    appId: '1:491750508291:ios:adcc37c6ff15bc0920cb36',
    messagingSenderId: '491750508291',
    projectId: 'chatfirebase-c252a',
    storageBucket: 'chatfirebase-c252a.firebasestorage.app',
    iosBundleId: 'com.example.globalchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5q9i-uYp-ukrsgGN8gCk7o7AQTElLoJs',
    appId: '1:491750508291:ios:adcc37c6ff15bc0920cb36',
    messagingSenderId: '491750508291',
    projectId: 'chatfirebase-c252a',
    storageBucket: 'chatfirebase-c252a.firebasestorage.app',
    iosBundleId: 'com.example.globalchat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_N4KoulVAihi6yLHhMRR719cHtoxxEg',
    appId: '1:491750508291:web:909d35f04e832dce20cb36',
    messagingSenderId: '491750508291',
    projectId: 'chatfirebase-c252a',
    authDomain: 'chatfirebase-c252a.firebaseapp.com',
    storageBucket: 'chatfirebase-c252a.firebasestorage.app',
  );

}